server:
  port: 8081

spring:
  application:
    name: BOOK-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/save_your_book
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
